const WORK_IN_PROGRESS_AVAILABLE = import.meta.env.DEV;

export const EPUB_READER_AVAILABLE = WORK_IN_PROGRESS_AVAILABLE;
export const ANIME_PLAYER_AVAILABLE = WORK_IN_PROGRESS_AVAILABLE;
export const GOOGLE_DRIVE_AVAILABLE = true;
